// Generated by https://quicktype.io

export interface YrResponse {
    route:        Route;
    locations:    Location[];
    roadCameras:  RoadCamera[];
    roadMessages: RoadMessage[];
    status:       Status;
    _links:       Links;
}

export interface Links {
    self:   Parent;
    parent: Parent;
}

export interface Parent {
    href: string;
}

export interface Location {
    id:        string;
    name:      string;
    urlPath:   string;
    elevation: number;
    position:  Position;
}

export interface Position {
    lat: number;
    lon: number;
}

export interface RoadCamera {
    name:      string;
    distance:  number;
    elevation: number;
    source:    string;
    sourceId:  number;
    position:  Position;
    views:     View[];
}

export interface View {
    images:      Images;
    description: string;
}

export interface Images {
    large:  Large;
    medium: Large;
    small:  Large;
}

export interface Large {
    url:    string;
    width:  number;
    height: number;
}

export interface RoadMessage {
    id:           string;
    locationName: string;
    message:      string;
    updated:      string;
    position:     Position;
    distance:     number;
    severity:     string;
    types:        string;
    startTime:    string;
    endTime:      string;
    openClosed:   OpenClosed;
}

export interface OpenClosed {
    isClosed:             boolean;
    isClosedForTheWinter: boolean;
    hasConvoyDriving:     boolean;
    partialClosed:        boolean;
}

export interface Route {
    id:            number;
    name:          string;
    urlPath:       string;
    collection:    string;
    lengthKm:      number;
    hasMessages:   boolean;
    cameraCount:   number;
    locationCount: number;
    openClosed:    OpenClosed;
    road:          Road;
}

export interface Road {
    number: string;
    type:   string;
    name:   string;
}

export interface Status {
    code: string;
}
